# **********************************************************************
#
# Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************

# Ice version 3.4.1

# <auto-generated>
#
# Generated from file `PermissionsVerifierF.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>

import Ice, IcePy, __builtin__

# Start of module Glacier2
_M_Glacier2 = Ice.openModule('Glacier2')
__name__ = 'Glacier2'

if not _M_Glacier2.__dict__.has_key('PermissionsVerifier'):
    _M_Glacier2._t_PermissionsVerifier = IcePy.declareClass('::Glacier2::PermissionsVerifier')
    _M_Glacier2._t_PermissionsVerifierPrx = IcePy.declareProxy('::Glacier2::PermissionsVerifier')

if not _M_Glacier2.__dict__.has_key('SSLPermissionsVerifier'):
    _M_Glacier2._t_SSLPermissionsVerifier = IcePy.declareClass('::Glacier2::SSLPermissionsVerifier')
    _M_Glacier2._t_SSLPermissionsVerifierPrx = IcePy.declareProxy('::Glacier2::SSLPermissionsVerifier')

# End of module Glacier2
