# **********************************************************************
#
# Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************

# Ice version 3.4.1

# <auto-generated>
#
# Generated from file `ConnectionF.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>

import Ice, IcePy, __builtin__

# Start of module Ice
_M_Ice = Ice.openModule('Ice')
__name__ = 'Ice'

if not _M_Ice.__dict__.has_key('ConnectionInfo'):
    _M_Ice._t_ConnectionInfo = IcePy.declareClass('::Ice::ConnectionInfo')

if not _M_Ice.__dict__.has_key('Connection'):
    _M_Ice._t_Connection = IcePy.declareClass('::Ice::Connection')

# End of module Ice
