# **********************************************************************
#
# Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************

# Ice version 3.4.1

# <auto-generated>
#
# Generated from file `PropertiesF.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>

import Ice, IcePy, __builtin__

# Start of module Ice
_M_Ice = Ice.openModule('Ice')
__name__ = 'Ice'

if not _M_Ice.__dict__.has_key('Properties'):
    _M_Ice._t_Properties = IcePy.declareClass('::Ice::Properties')

if not _M_Ice.__dict__.has_key('PropertiesAdmin'):
    _M_Ice._t_PropertiesAdmin = IcePy.declareClass('::Ice::PropertiesAdmin')
    _M_Ice._t_PropertiesAdminPrx = IcePy.declareProxy('::Ice::PropertiesAdmin')

# End of module Ice
