# **********************************************************************
#
# Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************

# Ice version 3.4.1

# <auto-generated>
#
# Generated from file `EndpointF.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>

import Ice, IcePy, __builtin__

# Start of module Ice
_M_Ice = Ice.openModule('Ice')
__name__ = 'Ice'

if not _M_Ice.__dict__.has_key('TCPEndpointInfo'):
    _M_Ice._t_TCPEndpointInfo = IcePy.declareClass('::Ice::TCPEndpointInfo')

if not _M_Ice.__dict__.has_key('UDPEndpointInfo'):
    _M_Ice._t_UDPEndpointInfo = IcePy.declareClass('::Ice::UDPEndpointInfo')

if not _M_Ice.__dict__.has_key('Endpoint'):
    _M_Ice._t_Endpoint = IcePy.declareClass('::Ice::Endpoint')

if not _M_Ice.__dict__.has_key('_t_EndpointSeq'):
    _M_Ice._t_EndpointSeq = IcePy.defineSequence('::Ice::EndpointSeq', (), _M_Ice._t_Endpoint)

# End of module Ice
